### ISSUE TITLE
docker image name mismatch

### ISSUE THREAD

**Issue by shimwell** [openmsr/msre#8]
In the run_docker.sh file the dockerfile name is 0.1.1

https://github.com/openmsr/msre/blob/ae944e2e86d6bc6de395901f60da873b7661daeb/msre_docker/run_docker.sh#L12

However the only docker image on dockerhub is 0.1.0

https://hub.docker.com/r/copenhagenatomics/msre/tags

wondering if docker hub is missing a newer version or if it is a typo in the script or perhaps I've misunderstood something

**Comment by aslakstubsgaard** [comment]
@ebknudsen are you still supporting this docker model?

**Comment by ebknudsen** [comment]
@shimwell @aslakstubsgaard Many apologies, soemhow this issue had slipped. I do still support this docker image though, the matter will be attended to shortly.

**Comment by bvhoof** [comment]
At the moment, the docker image is not in working condition due to a an issue with the DAGMC interface.

I am working on a new version of the docker image, 0.1.1 which fixes this.
Unfortunately, the 0.1.1 image is already pushed, but the DAGMC installer in the openmc_install_scripts repo is not working yet.

If you build the docker image yourself from the docker file with the build_docker.sh script, it will create a local version, which is compatible with this part of the flow.

I'll keep you posted when everything works.

**Comment by shimwell** [comment]
Thanks for the pointer, the local version works fine for me.
